name: firenet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.16
  - scipy<=1.6
  - pandas=0.25
  - matplotlib=3.1
  - scikit-learn=0.21.2
  - pytorch=1.2
  - skorch=0.6
  - astropy<=4.2
  - jupyterlab
  - ipywidgets<=7.5.1
