name: firenet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - skorch
  - astropy
  - jupyterlab
  - ipywidgets